### ISSUE TITLE
EntityVectorLinkExp returns NoneType - Error when calling the metaclass bases cannot create 'NoneType' instances

### ISSUE THREAD

**Issue by shauryr** [matthewfl/nlp-entity-convnet#2]
Traceback (most recent call last):
  File "runner.py", line 307, in <module>
    main()
  File "runner.py", line 247, in main
    queries_exp = **import**('exp_multi_conv_cosim').call_multi()
  File "/nlp-entity-convnet-master/exp_multi_conv_cosim.py", line 30, in <module>
    class EntityVectorLinkExp(baseModel):
TypeError: Error when calling the metaclass bases
    cannot create 'NoneType' instances

I get this error when I try to runner.py with all its arguments.
I have all the data needed and I have trained word2Vec also. 
Everything runs fine except 'Loading model'. Please tell what I may be missing.

**Comment by matthewfl** [comment]
Hi  shauryr,

it looks like the baseModel is still set to `None` which should be setup before you attempt to load 'exp_multi_conv_cosim'

https://github.com/matthewfl/nlp-entity-convnet/blob/master/runner.py#L236

Are you sure that you are running the latest version, as the line number that you have posted doesn't match what is currently in master.

**Comment by matthewfl** [comment]
I am going to assume that you have worked this issue out
