### ISSUE TITLE
mention type ace unrecognized

### ISSUE THREAD

**Issue by janenie** [matthewfl/nlp-entity-convnet#5]
Hi! I am running your demo.sh however I found that the -mentionType ace is not recognized, is there something wrong when you set up the berkeley joint model in the shell script ?

I am running on windows bash by the way

Thanks

**Comment by matthewfl** [comment]
1. I have never tried any of this code on windows and fairly skeptical that this is going to work without a lot of issues.  If you can use a linux machine or setup a virtual machine I am thinking that you are going to have a lot better time getting this working.
2. I am assuming that you aren't trying to pass the parameter `-mentionType ace` to the demo script
3. Can you try just running the command that is failing on its own without using the demo script?

**Comment by janenie** [comment]
Because I only have the gpu on windows server...I think I can only try if the code is working on linux with the same code

And I run the command with java using that berkeley-entity-assembly-1.jar in scala-2.11 folder, it just report that could not find or load main class edu.berkeley.nlp.entity.wiki.WikipediaInterface..

I actually do not know what is going on with this jar...

**Comment by janenie** [comment]
I modify some of the setting in this command, it is working to process the wiki dump, thanks anyway
$BENTITY -Xmx20g edu.berkeley.nlp.entity.wiki.WikipediaInterface -wikipediaDumpPath ../../data/$WIKIPEDIA_DUMP -mentionType "ace" -categoryDBInputPath ../../data/wikipedia-category-cache.ser.gz -outputPath ../../data/wikipedia-interface.ser.gz -datasetPaths $DP/data/ace05/dev/,$DP/data/ace05/test/,$DP/data/ace05/train/ -wikiStandoff $DP/data/ace05/ace05-all-conll-wiki/
